USE [master]
GO

/****** Object:  Database [MVC]    Script Date: 07/08/2013 21:17:24 ******/
CREATE DATABASE [MVC] ON  PRIMARY 
( NAME = N'MVC', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\MVC.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MVC_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\MVC_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MVC] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MVC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MVC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MVC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MVC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MVC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MVC] SET ARITHABORT OFF 
GO

ALTER DATABASE [MVC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MVC] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MVC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MVC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MVC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MVC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MVC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MVC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MVC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MVC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MVC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MVC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MVC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MVC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MVC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MVC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MVC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MVC] SET  READ_WRITE 
GO

ALTER DATABASE [MVC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MVC] SET  MULTI_USER 
GO

ALTER DATABASE [MVC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MVC] SET DB_CHAINING OFF 
GO


